name: Generate Premium Cybersecurity Content

on:
  schedule:
    - cron: '0 15 * * *'  # 11:00 AM EST (once daily for premium content)
  workflow_dispatch:      # Allow manual triggering

jobs:
  generate-premium-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests openai feedparser beautifulsoup4 pyyaml cryptography
        
    - name: Run Premium Content Generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        cd scripts
        python premium_content_generator.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add premium cybersecurity content - $(date +'%Y-%m-%d')"
          git push
        fi
